-- 계정 생성하면서 할당
CREATE USER c##OAuth2 IDENTIFIED BY 1234 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
-- 계정 권한 설정
GRANT CONNECT, RESOURCE TO c##OAuth2; 
GRANT CREATE VIEW, CREATE SYNONYM TO c##OAuth2; 
GRANT UNLIMITED TABLESPACE TO c##OAuth2; 
ALTER USER c##OAuth2 ACCOUNT UNLOCK;